### ISSUE TITLE
Example30.tsx scss incorrect?

### ISSUE THREAD

**Issue by baj1210** [ghiscoding/slickgrid-react#427]
### Describe the bug

(rgb(105 123 145 / 57%)) is not valid.

### Reproduction

run the code. it throws errors.

### Expectation

should be this:

.editable-field {
    // Use rgba for opacity
    background-color: rgba(105, 123, 145, 0.57) !important;
}

### Environment Info

```shell
npx envinfo --system --npmPackages 'slickgrid-react' --binaries --browsers

too much data dumped
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-react/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/slickgrid-react/wiki/HOWTO--Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-react/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
a Pull Request would be welcome

**Comment by baj1210** [comment]
should I be using the 6pac version?

**Comment by baj1210** [comment]
> a Pull Request would be welcome

I'm not very accustomed to github and pull requests. I would do one if I knew I would not cause an issue.

**Comment by ghiscoding** [comment]
I'm not sure why you mention the 6pac version, but FYI, Slickgrid-React uses Slickgrid-Universal and it was previously using the `6pac/slickgrid` dependency a while ago but that is not longer true since Slickgrid-React v4.x / Slickgrid-Universal v4.x (you can see this info in the [Migration Guide to v4](https://ghiscoding.gitbook.io/slickgrid-react/migrations/migration-to-4.x))

https://github.com/ghiscoding/slickgrid-react/blob/bf527682446004500d469fee67b9ce704764a55a/package.json#L85-L91


> I'm not very accustomed to github and pull requests. I would do one if I knew I would not cause an issue.

You can contribute directly from the GitHub page, just go to the file and click the edit button

![image](https://github.com/user-attachments/assets/99d9d593-bd0f-48be-937d-5ddefbd2fc30)

**Comment by baj1210** [comment]
I think it is because I completed the survey and got an email message referencing the 6pac repo?

Thanks for explaining how to do this. I have submitted a pull request and it looks like it is doing some automated tests.. it looks like it may have worked.

  Running:  example30.cy.ts                                                               (28 of 40)

  Example 30  Composite Editor Modal
    ✓ should display Example title (482ms)
    ✓ should have exact Column Pre-Header & Column Header Titles in the grid (60ms)
    ✓ should display 2 different tooltips when hovering icons on "Title" column (99ms)
    ✓ should have "TASK 0" (uppercase) incremented by 1 after each row (28ms)
    ✓ should be able to change "Duration" values of first 4 rows (607ms)
    ✓ should be able to change "Title" values of row indexes 1-3 (736ms)
    ✓ should be able to change "% Complete" values of row indexes 2-4 (229ms)
    ✓ should not be able to change the "Finish" dates on first 2 rows (156ms)
    ✓ should be able to change "Completed" values of row indexes 2-4 (542ms)
    ✓ should be able to change "Finish" values of row indexes 0-2 (542ms)
    ✓ should undo last edit and expect the date editor to be opened as well when clicking the associated last undo with editor button (125ms)
    ✓ should undo last edit and expect the date editor to NOT be opened when clicking undo last edit button (106ms)
    ✓ should click on the "Save" button and expect 2 console log calls with the queued items & also expect no more unsaved cells (86ms)
    ✓ should be able to toggle the grid to readonly (107ms)
    ✓ should be able to toggle back the grid to editable (188ms)
    ✓ should open the Composite Editor (Create Item) and expect all form inputs to be empty (118ms)
    ✓ should not be able to save, neither expect the modal window to close when having invalid fields (94ms)
    ✓ should fill in the (Create Item) form inputs and expect a new row in the grid (2714ms)
    ✓ should have new TASK 8888 displayed on first row (36ms)
    ✓ should open the Composite Editor (Edit Item) and expect all form inputs to be filled with TASK 8888 data of previous create item (1137ms)
    ✓ should have new TASK 8899 displayed on first row (31ms)
    ✓ should open the Composite Editor (Mass Update) and be able to change some of the inputs in the form (1418ms)
    ✓ should have updated values in the entire grid (61ms)
    ✓ should open the Composite Editor (Mass Update) change some inputs (1226ms)
    ✓ should be able to clear the "Country of Origin" autocomplete field in the modal form via the Clear button from the editor (90ms)
    ✓ should be able to click on the "Reset Form" button from the (Mass Update) and expect the form to be empty and not be able to Save (246ms)
    ✓ should have the "Mass Selection" button disabled when no rows are selected (9ms)
    ✓ should select row 1 and 2 (315ms)
    ✓ should be able to open the Composite Editor (Mass Selection) and be able to change some of the inputs in the form (767ms)
    ✓ should not have any row selected after the mass-selection save is over (81ms)
    ✓ should have updated all the changed values BUT only on the 2 selected rows (52ms)
    ✓ should open the Composite Editor (Mass Update) change "Percent Complete" to 100% and expect "Completed" to become checked and "Finish" date to be today's date (275ms)
    ✓ should not have any row selected after the mass-update save is over (79ms)
    ✓ should focus on first row and open the Composite Editor (Clone Item) and expect all form inputs to be filled with first row data (187ms)
    ✓ should change the "Title" & "Duration" from the Clone form, then click on "Cancel" button and expect no changes in the grid (343ms)
    ✓ should focus again on first row and open the Composite Editor (Clone Item) and expect all form inputs to be filled with first row data (169ms)
    ✓ should change the "Title" & "Duration" from the Clone form, then click on "Clone" button and expect a new row to show up on top of the grid (918ms)
    ✓ should expect original, that was originally used to clone, to now be exist as that 2nd row in the grid (21ms)
    ✓ should be able to clear the "Country of Origin" autocomplete field in the grid via the Clear button from the editor (194ms)
    ✓ should open Edit Composite Editor from Cell Menu and expect Task 4 on 6th row (283ms)
    ✓ should open Clone Composite Editor from Cell Menu and expect Task 4 on 6th row (275ms)
  41 passing (16s)
  (Results)
  ┌────────────────────────────────────────────────────────────────────────────────────────────
  │ Tests:        41                                                                               │
  │ Passing:      41                                                                               │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     15 seconds                                                                       │
  │ Spec Ran:     example30.cy.ts                                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────
─────────────────────────────────────────────────────────────────────────────────────────────
